#configuration for the MCP Command Server
[command_blocking]
# List of command substrings that will be blocked if found in the user's input command.
prohibited_commands = [
    "rm ",
    "mv ",
    "sudo ",
    "su ",
]
override = false
restricted_files = [
    "mcp_server_command_enh.py",
    "mcp_server_command.log",
    "pexpect_auto.py",
    "config.toml",
    "mcp_server_command*.py"
]

[models.mistral_1]
name = "mistral-large-2512"
temperature = 0.7
top_k = 1
base_url = "https://api.mistral.ai/v1"
api_key = "MISTRAL_API_KEY"

[models.gemini_flash]
# Gemini Model running on Google's OpenAI-compatible endpoint
name = "gemini-2.5-flash"
temperature = 0.0
top_k = 1
base_url = "https://generativelanguage.googleapis.com/v1beta/openai/"
api_key = "GEMINI_API_KEY"

[models.gemini_pro]
# Another Gemini model
name = "gemini-2.5-pro"
temperature = 0.0
top_k = 1
base_url = "https://generativelanguage.googleapis.com/v1beta/openai/"
api_key = "GEMINI_API_KEY"

[models.gemma_3]
# Another model, same endpoint
name = "gemma-3-27b-it"
temperature = 0.2
top_k = 1
base_url = "https://generativelanguage.googleapis.com/v1beta/openai/"
api_key = "GEMINI_API_KEY"

[models.openai_gpt4]
# Example of a different vendor (OpenAI)
name = "gpt-4o"
temperature = 0.1
top_k = 1 # Ignored by OpenAI, kept for consistency
base_url = "https://api.openai.com/v1"
api_key = "OPENAI_API_KEY"

[models.nova_2]
name = "amazon/nova-2-lite-v1:free"
temperature = 0.9
top_k = 1
base_url = "https://openrouter.ai/api/v1"
api_key = "OPENROUTER_API_KEY"

[models.nvida_1]
name = "nvidia/nemotron-nano-12b-v2-vl:free"
temperature = 0.7
top_k = 1
base_url = "https://openrouter.ai/api/v1"
api_key = "OPENROUTER_API_KEY"


[models.gpt_oss_20b]
name = "openai/gpt-oss-20b:free"
temperature = 0.7
top_k = 1
base_url = "https://openrouter.ai/api/v1"
api_key = "OPENROUTER_API_KEY"


[models.devstral_1]
name = "devstral-2512"
temperature = 0.7
top_k = 1
base_url = "https://api.mistral.ai/v1"
api_key = "MISTRAL_API_KEY"

# If override set to True, all command restrictions are ignored and execution is permitted.
